version: 0.0
os: linux
files:
  - source: /src/main.ts
    destination: /root
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
  ApplicationStart:
    - npm run start
  ApplicationStop:
    - npm run stop
      runas: root
