version: 0.0
os: linux
files:
  - source: main.ts
    destination: /src/
hooks:
  BeforeInstall:
    - npm install
      runas: root
  ApplicationStart:
    - npm run start
  ApplicationStop:
    - npm run stop
      runas: root
