version: 0.0
os: linux
files:
  - source: /
    destination: /root/MyGitHub2
hooks:
  BeforeInstall:
    - location: /scripts/install_dependencies.sh
  AfterInstall:
    - location: /scripts/after_install.sh
  ApplicationStart:
    - location: /gscripts/start_server.sh
    